:: ACTUALIZAR PALABRAS CLAVES USADAS EN PLANTILLA BASE PARA LA TEENSY 3.2
:: AUTOR: HELLOWORLD

ECHO OFF & CLS
SET RUTA="%SYSTEMDRIVE%\Program Files (x86)\Arduino\hardware\teensy\avr\keywords.txt"
IF NOT EXIST %RUTA% ( GOTO :ERRORNOFILE) ELSE ( GOTO :APPLYUPDATE)




:ERRORNOFILE
COLOR>NUL 0C
ECHO.
ECHO [*] ERROR NO SE HA ENCONTRADO EL ARCHIVO: %RUTA%
ECHO [*] SI CREE QUE ES UNO DIFERENTE SIENTASÉ LIBRE DE MODIFICAR ESTE BAT
PAUSE>NUL
EXIT

:APPLYUPDATE

FOR /F %%A IN ('MORE %RUTA% ^| FINDSTR C:"# TEENSY 32 PLANTILLA BASE"') DO SET UPDATED=OK

IF [%UPDATED%] EQU [OK] (
COLOR>NUL 0E
ECHO.
ECHO [*] ERROR LAS PALABRAS CLAVES YA SE ENCUENTRAN ACTUALIZADAS
PAUSE>NUL
EXIT
)

echo. >> %RUTA%
echo # TEENSY 32 PLANTILLA BASE>> %RUTA%

:: REVISAR SI TIENE PERMISOS SUFICIENTE PARA ESCRIBIR EN EL ARCHIVO
SET NEEDADMIN=TRUE
FOR /F %%A IN ('MORE %RUTA% ^| FINDSTR C:"# TEENSY 32 PLANTILLA BASE"') DO SET NEEDADMIN=FALSE

IF NOT [%NEEDADMIN%] EQU [FALSE] (
	COLOR>NUL C
	ECHO.
	ECHO [*] ERROR INICIAR COMO ADMINISTRADOR
	PAUSE>NUL
	EXIT
)

echo. >> %RUTA%
echo Escribir	KEYWORD2>> %RUTA%
echo escribir	KEYWORD2>> %RUTA%
echo CTRL	KEYWORD2>> %RUTA%
echo SHIFT	KEYWORD2>> %RUTA%
echo GUI	KEYWORD2>> %RUTA%
echo ALT	KEYWORD2>> %RUTA%
echo ALTGR	KEYWORD2>> %RUTA%
echo CTRL_ALT	KEYWORD2>> %RUTA%
echo CTRL_SHIFT	KEYWORD2>> %RUTA%
echo GUI_SHIFT	KEYWORD2>> %RUTA%
echo Arriba	KEYWORD2>> %RUTA%
echo Abajo	KEYWORD2>> %RUTA%
echo Izq	KEYWORD2>> %RUTA%
echo Der	KEYWORD2>> %RUTA%
echo Enter	KEYWORD2>> %RUTA%
echo Tab	KEYWORD2>> %RUTA%
echo Tecla	KEYWORD2>> %RUTA%
echo. >> %RUTA%
echo A	LITERAL1>> %RUTA%
echo B	LITERAL1>> %RUTA%
echo C	LITERAL1>> %RUTA%
echo D	LITERAL1>> %RUTA%
echo E	LITERAL1>> %RUTA%
echo F	LITERAL1>> %RUTA%
echo G	LITERAL1>> %RUTA%
echo H	LITERAL1>> %RUTA%
echo I	LITERAL1>> %RUTA%
echo J	LITERAL1>> %RUTA%
echo K	LITERAL1>> %RUTA%
echo L	LITERAL1>> %RUTA%
echo M	LITERAL1>> %RUTA%
echo N	LITERAL1>> %RUTA%
echo N_	LITERAL1>> %RUTA%
echo O	LITERAL1>> %RUTA%
echo P	LITERAL1>> %RUTA%
echo Q	LITERAL1>> %RUTA%
echo R	LITERAL1>> %RUTA%
echo S	LITERAL1>> %RUTA%
echo T	LITERAL1>> %RUTA%
echo U	LITERAL1>> %RUTA%
echo V	LITERAL1>> %RUTA%
echo W	LITERAL1>> %RUTA%
echo X	LITERAL1>> %RUTA%
echo Y	LITERAL1>> %RUTA%
echo Z	LITERAL1>> %RUTA%
echo. >> %RUTA%
echo N_0	LITERAL1>> %RUTA%
echo N_1	LITERAL1>> %RUTA%
echo N_2	LITERAL1>> %RUTA%
echo N_3	LITERAL1>> %RUTA%
echo N_4	LITERAL1>> %RUTA%
echo N_5	LITERAL1>> %RUTA%
echo N_6	LITERAL1>> %RUTA%
echo N_7	LITERAL1>> %RUTA%
echo N_8	LITERAL1>> %RUTA%
echo N_9	LITERAL1>> %RUTA%
echo. >> %RUTA%
echo F1	LITERAL1>> %RUTA%
echo F2	LITERAL1>> %RUTA%
echo F3	LITERAL1>> %RUTA%
echo F4	LITERAL1>> %RUTA%
echo F5	LITERAL1>> %RUTA%
echo F6	LITERAL1>> %RUTA%
echo F7	LITERAL1>> %RUTA%
echo F8	LITERAL1>> %RUTA%
echo F9	LITERAL1>> %RUTA%
echo F10	LITERAL1>> %RUTA%
echo F11	LITERAL1>> %RUTA%
echo F12	LITERAL1>> %RUTA%
echo. >> %RUTA%
echo CTRL_IZQ	LITERAL1>> %RUTA%
echo CTRL_DER	LITERAL1>> %RUTA%
echo SHIFT_IZQ	LITERAL1>> %RUTA%
echo SHIFT_DER	LITERAL1>> %RUTA%
echo GUI_IZQ	LITERAL1>> %RUTA%
echo GUI_DER	LITERAL1>> %RUTA%
echo ALT_IZQ	LITERAL1>> %RUTA%
echo ALT_DER	LITERAL1>> %RUTA%
echo. >> %RUTA%
echo ESC	LITERAL1>> %RUTA%
echo TABULADOR	LITERAL1>> %RUTA%
echo BLOQ_MAYUS	LITERAL1>> %RUTA%
echo ESPACIO	LITERAL1>> %RUTA%
echo ENTER	LITERAL1>> %RUTA%
echo BORRAR	LITERAL1>> %RUTA%
echo IMP_PNT	LITERAL1>> %RUTA%
echo SUPR	LITERAL1>> %RUTA%
echo INICIO	LITERAL1>> %RUTA%
echo FIN	LITERAL1>> %RUTA%
echo AV_PAG	LITERAL1>> %RUTA%
echo RE_PAG	LITERAL1>> %RUTA%
echo. >> %RUTA%
echo ARRIBA	LITERAL1>> %RUTA%
echo ABAJO	LITERAL1>> %RUTA%
echo IZQUIERDA	LITERAL1>> %RUTA%
echo DERECHA	LITERAL1>> %RUTA%

COLOR>NUL 0E
ECHO SE HAN ACTUALIZADO LAS PALABRAS CLAVES (KEYWORDs)
PAUSE>NUL

exit